name: CI - E2E Cypress + Allure

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      # 🔥 Instalar libs necessárias pro Cypress rodar no CI
      - name: Instalar dependências do sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk2.0-0 \
            libgtk-3-0 \
            libgbm-dev \
            libnotify-dev \
            libgconf-2-4 \
            libnss3 \
            libxss1 \
            libasound2 \
            libxtst6 \
            xauth \
            xvfb

      # 🔥 Rodar Cypress corretamente (headless real)
      - name: Rodar Cypress
        run: xvfb-run npx cypress run --browser chrome

      # 🔥 Baixar histórico anterior (trend)
      - name: Baixar histórico anterior
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
        continue-on-error: true

      # 🔥 Copiar histórico corretamente
      - name: Copiar histórico
        run: |
          if [ -d gh-pages/history ]; then
            mkdir -p allure-results/history
            cp -r gh-pages/history/* allure-results/history/
          fi

      # 🔥 Garantir pasta antes de criar executor
      - name: Add executor info
        run: |
          mkdir -p allure-results
          echo '{
            "name": "GitHub Actions",
            "type": "github",
            "buildName": "E2E Cypress",
            "buildUrl": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }' > allure-results/executor.json

      # 🔥 Gerar relatório Allure
      - name: Gerar Allure Report
        run: npx allure generate allure-results --clean -o allure-report

      # 🚀 Deploy no GitHub Pages
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          keep_files: true
