name: Cypress + Allure Report (GitHub Pages)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run Cypress tests
        run: yarn ci

      - name: Generate Allure Report
        run: |
          yarn allure generate allure-results --clean -o allure-report

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          publish_branch: gh-pages
